# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e873fbb2a64b85f729358900b717bcf5bd26f068bb2a676c4e52dcb1056cd3c99008ca6880f4bf7b7385d5d8de807f7f2d7fb6230cf136c41cfe41568900dd33

test:
  secret_key_base: a5c33b96f3ce26a303f4aa066f111deb54908b0be0c32c0c8611082ab63a3d252570012565f00b983e4224744803432396878e4b319ccd47a4064e5f0b3da5f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
